### ISSUE TITLE
Not compatible with fenix 7

### ISSUE THREAD

**Issue by JaskaRoman** [gcaufield/TogglIQ#40]
## Describe the bug
It is currently not possible to install the app on a fenix 7 watch as it's not on the compatibility list.

## To Reproduce
Try to install the app on a fenix 7.

## Expected Behavior
Being able to install on a fenix 7.

## Actual Behavior
The app store will not allow installation from web and will not even find the app from the mobile app.

## Devices Tested
fenix 7S FW 7.24

**Comment by gcaufield** [comment]
New Version Released.
